[log]
  level="DEBUG"
  filePath="/tmp/log/traefik.log"
[accessLog]
  filePath = "/tmp/log/access.log"
  
[retry]
 attempts = 3

################################################################
# Docker configuration backend
################################################################
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

################################################################
# ACME Let's Encrypt 
################################################################
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.myresolver]
    [certificatesResolvers.myresolver.acme]
      email = ""
      storage = "acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [certificatesResolvers.myresolver.acme.tlsChallenge]
      [certificatesResolvers.myresolver.acme.httpChallenge]
	entryPoint = "http"
